hotel/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import include, path
from django.shortcuts import redirect
from django.views.i18n import set_language
from django.utils.translation import get_language


def root_redirect(request):
    lang = get_language() or "en"
    return redirect(f"/{lang}/")


urlpatterns = [
    path("", root_redirect),
    path("admin/", admin.site.urls),
    path("i18n/setlang/", set_language, name="set_language"),
]

urlpatterns += i18n_patterns(
    path("", include(("main.urls", "main"), namespace="main")),
    path("", include(("booking.urls", "booking"), namespace="booking")),
    prefix_default_language=True,
)

main/urls.py
from django.urls import path
from main import views
from .views import RoomListView, RoomDetailView, Contact, MainPageView


app_name = 'main'

urlpatterns = [
    path("", MainPageView.as_view(), name="index"),
    path("сottages/", RoomListView.as_view(), name="rooms"),
    path("сottages/<slug:slug>/", RoomDetailView.as_view(), name="room"),
    path("amenities/", views.amenities, name="amenities"),
    path("location/", views.location, name="location"),
    path("terms/", views.terms, name="terms"),
    path("privacy/", views.privacy, name="privacy"),
    path("gallery/", views.gallery, name="gallery"),
    path("contact/", Contact.as_view(), name="contact"),
]

templates/includes/footer.html
{% load static %}
{% load i18n %}
  
  <footer id="footer" class="footer position-relative dark-background">

    <div class="footer-top">
      <div class="container">
        <div class="row gy-4">
          <div class="col-lg-4 col-md-6 footer-about">
            <a href="{% url "main:index" %}" class="logo d-flex align-items-center">
              <span class="sitename">WOOD LIFE</span>
            </a>
            <div class="footer-contact pt-3">
              <p>{{ site_address| default:"A108 Adam Street" }}</p>
              <p>{{ site_city| default:"New York, NY 535022" }}</p>
              <p class="mt-3"><strong>{% trans "Phone:" %}</strong> <span>{{ site_phone| default:""}}</span></p>
              <p><strong>Email:</strong> <span>{{site_email| default:""}}</span></p>
            </div>
          </div>

          <div class="col-lg-4 col-md-6 footer-links">
            <h4>{% trans "Useful Links" %}</h4>
            <ul>
              <li><a href="{% url "main:index" %}">{% trans "Home" %}</a></li>
              <li><a href="{% url "main:rooms" %}">{% trans "Cottages" %}</a></li>
              <li><a href="{% url "main:amenities" %}">{% trans "Amenities" %}</a></li>
              <li><a href="{% url "main:location" %}">{% trans "Location" %}</a></li>

            </ul>
          </div>

          <div class="col-lg-4 col-md-6 footer-links">
            <h4>{% trans "Legal" %}</h4>
            <ul>
              <li><a href="{% url "main:terms" %}">{% trans "Terms of service" %}</a></li>
              <li><a href="{% url "main:privacy" %}">{% trans "Privacy policy" %}</a></li>
            </ul>
          </div>

        </div>
      </div>
    </div>

    <div class="copyright text-center">
      <div class="container d-flex flex-column flex-lg-row justify-content-center justify-content-lg-between align-items-center">

        <div class="d-flex flex-column align-items-center align-items-lg-start">
          <div>
            © Copyright <strong><span>MyWebsite</span></strong>. All Rights Reserved
          </div>
          <div class="credits">
            <!-- All the links in the footer should remain intact. -->
            <!-- You can delete the links only if you purchased the pro version. -->
            <!-- Licensing information: https://bootstrapmade.com/license/ -->
            <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/herobiz-bootstrap-business-template/ -->
            Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a> | <a href="https://bootstrapmade.com/tools/">DevTools</a>
          </div>
        </div>

        <div class="social-links order-first order-lg-last mb-3 mb-lg-0">
          <a href="{{site_twitter| default:"#"}}"><i class="bi bi-twitter-x"></i></a>
          <a href="{{site_facebook| default:"#"}}"><i class="bi bi-facebook"></i></a>
          <a href="{{site_instagram| default:"#"}}"><i class="bi bi-instagram"></i></a>
          <a href="{{site_linkedin| default:"#"}}"><i class="bi bi-linkedin"></i></a>
        </div>

      </div>
    </div>

  </footer>

templates/includes/header.html
{% load static %}
{% load i18n %}
{% get_current_language as CURRENT_LANG %}
{% get_available_languages as LANGUAGES %}
{% get_language_info_list for LANGUAGES as languages %}


  <header id="header" class="header sticky-top">

    <div class="topbar d-flex align-items-center dark-background">
      <div class="container d-flex justify-content-center justify-content-md-between">
        <div class="contact-info d-flex align-items-center">
          <i class="bi bi-envelope d-flex align-items-center"><a href="mailto:contact@example.com">{{site_email| default:""}}</a></i>
          <i class="bi bi-phone d-flex align-items-center ms-4"><span>{{ site_phone| default:""}}</span></i>
        </div>
        <div class="social-links d-none d-md-flex align-items-center">
          <a href="{{site_twitter| default:"#"}}"><i class="bi bi-twitter-x"></i></a>
          <a href="{{site_facebook| default:"#"}}"><i class="bi bi-facebook"></i></a>
          <a href="{{site_instagram| default:"#"}}"><i class="bi bi-instagram"></i></a>
          <a href="{{site_linkedin| default:"#"}}"><i class="bi bi-linkedin"></i></a>
        </div>
      </div>
    </div><!-- End Top Bar -->

    <div class="branding d-flex align-items-cente">

      <div class="container position-relative d-flex align-items-center justify-content-between">
        <a href="{% url "main:index" %}" class="logo d-flex align-items-center">
          <img src="{% static "assets/img/logo.png" %}" alt="Wood Life" width="220" height="100">
        </a>

        <nav id="navmenu" class="navmenu">
          <ul>
            <li><a href="{% url "main:index" %}" class="active">{% trans "Home" %}</a></li>
            <li><a href="{% url "main:rooms" %}">{% trans "Cottages" %}</a></li>
            <li><a href="{% url "main:amenities" %}">{% trans "Amenities" %}</a></li>
            <li><a href="{% url "main:location" %}">{% trans "Location" %}</a></li>
            <li class="dropdown"><a href="#"><span>{% trans "Info" %}</span> <i class="bi bi-chevron-down toggle-dropdown"></i></a>
              <ul>
                <li><a href="{% url "main:gallery" %}">{% trans "Gallery" %}</a></li>
                <li><a href="{% url "main:terms" %}">{% trans "Terms Page" %}</a></li>
                <li><a href="{% url "main:privacy" %}">{% trans "Privacy Page" %}</a></li>
              </ul>
            </li>
            <li><a href="{% url "main:contact" %}">{% trans "Contact" %}</a></li>

            {% include "includes/language_switch.html" %}

          </ul>
          <i class="mobile-nav-toggle d-xl-none bi bi-list"></i>
        </nav>

      </div>

    </div>

  </header>

templates/includes/language_switch.html
{% load i18n %}

<li class="dropdown">

  <a href="#">
    <svg class="icon" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
      <g id="SVGRepo_iconCarrier">
        <path fill-rule="evenodd" clip-rule="evenodd"
          d="M4 0H6V2H10V4H8.86807C8.57073 5.66996 7.78574 7.17117 6.6656 8.35112C7.46567 8.73941 8.35737 8.96842 9.29948 8.99697L10.2735 6H12.7265L15.9765 16H13.8735L13.2235 14H9.77647L9.12647 16H7.0235L8.66176 10.9592C7.32639 10.8285 6.08165 10.3888 4.99999 9.71246C3.69496 10.5284 2.15255 11 0.5 11H0V9H0.5C1.5161 9 2.47775 8.76685 3.33437 8.35112C2.68381 7.66582 2.14629 6.87215 1.75171 6H4.02179C4.30023 6.43491 4.62904 6.83446 4.99999 7.19044C5.88743 6.33881 6.53369 5.23777 6.82607 4H0V2H4V0ZM12.5735 12L11.5 8.69688L10.4265 12H12.5735Z"
          fill="currentColor">
        </path>
      </g>
    </svg>

    {% get_current_language as LANGUAGE_CODE %}
    <span>
      {% if LANGUAGE_CODE == "uk" %}
        Українська
      {% else %}
        English
      {% endif %}
    </span>

    <i class="bi bi-chevron-down toggle-dropdown"></i>
  </a>

  <ul>
    <li>
      <a href="#"
         onclick="document.getElementById('lang-uk').submit(); return false;">
        Українська
      </a>
    </li>

    <li>
      <a href="#"
         onclick="document.getElementById('lang-en').submit(); return false;">
        English
      </a>
    </li>
  </ul>

  <!-- Hidden Forms -->
  <form id="lang-uk" action="{% url 'set_language' %}" method="post" style="display:none;">
    {% csrf_token %}
    <input type="hidden" name="language" value="uk">
    <input type="hidden" name="next" value="{{ request.path }}">
  </form>

  <form id="lang-en" action="{% url 'set_language' %}" method="post" style="display:none;">
    {% csrf_token %}
    <input type="hidden" name="language" value="en">
    <input type="hidden" name="next" value="{{ request.path }}">
  </form>

</li>